@ContosoPizza_HostAddress = http://0.0.0.0:5084

###

GET {{ContosoPizza_HostAddress}}/pizzas/
Accept: application/json

###

GET {{ContosoPizza_HostAddress}}/pizzas/4
Accept: application/json

###


POST {{ContosoPizza_HostAddress}}/register/
Content-Type: application/json

{
  "email": "me@example.com",
  "password": "P@ssword1"
}

###


# @name loginRequest
POST {{ContosoPizza_HostAddress}}/login/
Content-Type: application/json
{
  "email": "me@example.com",
  "password": "P@ssword1"
}

###


POST {{ContosoPizza_HostAddress}}/logout/
Content-Type: application/json

###

POST {{ContosoPizza_HostAddress}}/pizzas/
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Content-Type: application/json

{
    "id": 4,
    "name": "GF Buffalo Chicken"
}

###

PUT {{ContosoPizza_HostAddress}}/pizzas
Authorization: Bearer {{loginRequest.response.body.accessToken}}
Content-Type: application/json

{
    "id": 4,
    "name": "GF Buffalo Chicken, for those that like it spicy"
}

###

DELETE {{ContosoPizza_HostAddress}}/pizza/2

###
